services:
    minio:
        image: minio/minio
        container_name: minio
        command: server /data --console-address ":9001"
        ports:
        - "9000:9000"
        - "9001:9001"
        env_file:
        - .env
        volumes:
        - ./data:/data
        restart: always

    postgres:
        image: postgres:13
        container_name: postgres
        ports:
        - "5432:5432"
        env_file:
        - .env
        volumes:
        - ./data:/var/lib/postgresql/data
        restart: always