services:
  minio:
    image: minio/minio
    container_name: 'minio'
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./tmp/minio:/data
    environment:
      MINIO_ROOT_USER: rootuser
      MINIO_ROOT_PASSWORD: rootpassword
    command: server --console-address ":9001" /data
  
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/tmp/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/tmp/rabbitmq/log/:/var/log/rabbitmq