services:
    minio:
        image: minio/minio
        container_name: minio
        command: server /data --console-address ":9001"
        ports:
        - "9000:9000"
        - "9001:9001"
        env_file:
        - .env
        volumes:
        - ./data:/data
        networks:
        - minio
        restart: always

networks:
    minio:
        driver: bridge