services:
    minio:
        image: minio/minio
        container_name: minio
        command: server /data --console-address ":9001"
        ports:
        - "9000:9000"
        - "9001:9001"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        volumes:
        - ./data:/data
        networks:
        - minio
        restart: always

networks:
    minio:
        driver: bridge